media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Publication Date, type: date }
      - { name: modDatetime, label: Modified Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
  - name: projets
    label: Projets
    type: collection
    path: src/content/projets
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: slug, label: Slug, type: string }
      - { name: description, label: Description, type: string }
      - { name: pubDate, label: Publication Date, type: date }
      - { name: ogImage, label: Title, type: string }
      - { name: link, label: Link, type: string }
      - { name: github, label: GitHub, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
      - { name: image, label: Image, type: image, options: { input: public/assets/projets, output: /assets/projets } }